Models/ErrorViewModel.cs
namespace GERNALE_WEB_APP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using GERNALE_WEB_APP.Models;
using Microsoft.AspNetCore.Mvc;

namespace GERNALE_WEB_APP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SectionController.cs
using GERNALE_WEB_APP.Core.Interface;
using GERNALE_WEB_APP.Core.Model;
using Microsoft.AspNetCore.Mvc;

namespace GERNALE_WEB_APP.Controllers
{
    public class SectionController : Controller
    {
        private readonly ISectionService sectionRepository;

        public SectionController(ISectionService sectionRepository)
        {
            this.sectionRepository = sectionRepository;
        }

        public IActionResult Index()
        {
            return View(MyDatabase.sections);
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Add(Section section)
        {
            Section searchedSection = MyDatabase.sections.Find(x => x.Name == section.Name);
            if (searchedSection == null)
            {
                if (MyDatabase.sections.Count > 0)
                {
                    int id = MyDatabase.sections[MyDatabase.sections.Count - 1].Id + 1;
                    section.Id = id;
                    MyDatabase.sections.Add(section);
                    return RedirectToAction("Index");
                }
                else
                {
                    section.Id = 1;
                    MyDatabase.sections.Add(section);
                    return RedirectToAction("Index");
                }
            }
            else
            {
                ViewData["error"] = true;
                ViewData["message"] = "Section already exist.";
                return View("Create", searchedSection);
            }
        }

        public IActionResult Edit(int id)
        {
            return View(sectionRepository.GetSectionById(id));
        }

        public IActionResult Save(Section section)
        {
            sectionRepository.SaveSection(section);
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            return View(sectionRepository.GetSectionById(id));
        }

        public IActionResult Delete(int id)
        {
            Console.WriteLine(id);
            Section section = MyDatabase.sections.Find(x => x.Id == id);
            if (section.Students.Count > 0)
            {
                return BadRequest("Can't delete section. Student list is not empty.");
            }
            else
            {
                int index = MyDatabase.sections.FindIndex(x => x.Id == id);
                MyDatabase.sections.RemoveAt(index);
                return Ok("Section successfully deleted.");
            }
        }

        [HttpPost]
        public IActionResult Assign(int id, [FromBody] List<StudentId> list)
        {
            var studentList = sectionRepository.GetSectionById(id).Students;
            foreach (var idList in list)
            {
                studentList.Add(idList.id);
                Student student = MyDatabase.students.Find(x => x.Id == idList.id);
                student.SectionId = id;
            }
            return Ok("Student assigned successfully!");
        }

        public IActionResult Remove(int id, int studentId)
        {
            Section section = MyDatabase.sections.Find(x => x.Id == id);
            int studentIndex1 = section.Students.FindIndex(x => x == studentId);
            section.Students.RemoveAt(studentIndex1);
            int studentIndex2 = MyDatabase.students.FindIndex(x => x.Id == studentId);
            MyDatabase.students[studentIndex2].SectionId = 0;
            return Ok("Student successfully removed from this section.");
        }
    }

    public class StudentId()
    {
        public int id { get; set; }
    }
}

Controllers/StudentController.cs
using GERNALE_WEB_APP.Core.Interface;
using GERNALE_WEB_APP.Core.Model;
using GERNALE_WEB_APP.Infrastructure.Repository;
using Microsoft.AspNetCore.Mvc;

namespace GERNALE_WEB_APP.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentService studentRepository;

        public StudentController(IStudentService studentRepository)
        {
            this.studentRepository = studentRepository;
        }

        public IActionResult Index()
        {
            return View(studentRepository.GetAllStudents());
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Add(Student student)
        {
            if (MyDatabase.students.Find(x => x.StudentNumber == student.StudentNumber) != null)
            {
                ViewData["error"] = true;
                ViewData["message"] = "Student already exist.";
                return View("Create", student);
            } 
            else
            {
                if (MyDatabase.students.Count > 0)
                {
                    int id = MyDatabase.students[MyDatabase.students.Count - 1].Id + 1;
                    student.Id = id;
                    studentRepository.AddStudent(student);
                    return RedirectToAction("Index");
                }
                else
                {
                    student.Id = 1;
                    studentRepository.AddStudent(student);
                    return RedirectToAction("Index");
                }
            }
        }

        public IActionResult Edit(int id)
        {
            return View(studentRepository.GetStudent(id));
        }

        public IActionResult Save(Student student)
        {
            int index = MyDatabase.students.FindIndex(x => x.Id == student.Id);
            MyDatabase.students[index] = student;
            return RedirectToAction("Index");
        }

        public IActionResult Details(int id)
        {
            return View(studentRepository.GetStudent(id));
        }

        public IActionResult Delete(int id)
        {
            if (MyDatabase.students.Count > 0)
            {
                Student student = MyDatabase.students.Find(x => x.Id == id);
                if (student.SectionId == 0)
                {
                    int index = MyDatabase.students.FindIndex(x => x.Id == student.Id);
                    MyDatabase.students.RemoveAt(index);
                    return Ok("Student record successfully deleted.");
                }
                else
                {
                    return BadRequest("Failed to delete! Student is currently registered to a section.");
                }
            }
            else
            {
                return Ok("Empty student record.");
            }
        }

        public IActionResult GetFilteredList(int id)
        {
            var list = studentRepository.GetAllStudents().Where(x => x.SectionId != id && x.SectionId == 0).ToList();
            return Ok(list);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Section/Create.cshtml
@model GERNALE_WEB_APP.Core.Model.Section

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Section</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @if (ViewData["error"] != null && Convert.ToBoolean(ViewData["error"]) == true)
        {
            <div class="alert alert-danger" role="alert">
                @ViewData["message"]
            </div>
        }

        <form method="post" asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Section/Details.cshtml
@model GERNALE_WEB_APP.Core.Model.Section

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Section</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            <div id="section-id">@Html.DisplayFor(model => model.Id)</div>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

<div class="modal fade" id="modal-assign-student">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Assign Students</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body bg-light" id="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="btn-save">Save changes</button>
            </div>
        </div>
    </div>
</div>

<div class="mt-4">
    <div class="d-flex justify-content-between">
        <h4>List of Students</h4>
        <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal-assign-student" id="btn-assign">Assign Student</button>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Student Number
                </th>
                <th>
                    Name
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var studentId in Model.Students)
            {
                var student = MyDatabase.students.Find(x => x.Id == studentId);
                <tr>
                    <td>
                        @student.StudentNumber
                    </td>
                    <td>
                        @student.FirstName @student.LastName
                    </td>
                    <td>
                        @Html.ActionLink("Remove", "Remove", new { id = Model.Id, studentId = studentId }, new { @class = "btn-remove"})
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script>
    $(".btn-remove").on('click', function(event) {
        event.preventDefault();
        if (confirm('Are you sure you want to remove this student?')) {
            $.ajax({
                type: "delete",
                url: $(this).attr('href'),
                success : function(response) {
                    alert(response);
                    location.reload();
                },
                error: function(error){
                    alert(error.responseText);
                }
            });
        }
    });

    $("#btn-assign").click(function(){
        $("#modal-body").html("");
        $.ajax({
            type: "get",
            url: "/Student/GetFilteredList/" + $("#section-id").text(),
            success: function(response) {
                var list = JSON.parse(JSON.stringify(response));
                for(var i = 0; i < list.length; i++) {
                    var data = list[i];
                    $("#modal-body").append(
                        '<div class=" d-flex align-items-center bg-white px-2 py-0 mb-2">\n' +
                            '<input class="form-check-input me-2" type="checkbox" value='+data.id+' id="chb-student">' +
                            '<div>' +
                                '<p>' +
                                        '<div class="h6">' + data.firstName + ' ' + data.lastName + '</div>' +
                                        '<span class="text-body-secondary">' + data.studentNumber + '</span>' +
                                    '</p>' +
                            '</div>' +
                        '</div>'
                    );
                }
            },
            error: function(error) {
                alert(error.responseText);
            }
        });
    });

    $("#btn-save").click(function(){
        var studentIds = [];
        $("input").each(function(){
            var checkbox = $(this);
            if (checkbox.is(":checked")) {
                studentIds.push({
                    id: parseInt(checkbox.val())
                });
            }
        });

        if (studentIds.length == 0) {
            alert("No students selected.")
        } else {
            $.ajax({
                type: "post",
                url: "/Section/Assign/" + $("#section-id").text(),
                contentType: "application/json",
                data: JSON.stringify(studentIds),
                success: function(response) {
                    alert(response);
                    location.reload();
                },
                error: function(error) {
                    console.log(error.responseText);
                }
            });
        }
    });
</script>

Views/Section/Edit.cshtml
@model GERNALE_WEB_APP.Core.Model.Section

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Section</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Save">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" readonly />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Section/Index.cshtml
@model IEnumerable<GERNALE_WEB_APP.Core.Model.Section>

@{
    ViewData["Title"] = "Sections";
}

<h1>Sections</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
@if (ViewData["error"] != null && Convert.ToBoolean(ViewData["error"]) == true)
{
    <div class="alert alert-danger" role="alert">
        @ViewData["message"]
    </div>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Total No. of Students
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @item.Students.Count
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "delete-btn" })
            </td>
        </tr>
}
    </tbody>
</table>

<script>
    $(".delete-btn").on('click', function(event){
        event.preventDefault();
        if (confirm('Are you sure you want to delete this section?')) {
            $.ajax({
                type: "delete",
                url: $(this).attr('href'),
                success : function(response) {
                    alert(response);
                    location.reload();
                },
                error: function(error){
                    alert(error.responseText);
                }
            });
        }
    });
</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Student Section Management System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GERNALE_WEB_APP.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Student Section Management System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Section" asp-action="Index">Sections</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Student Section Management System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Student/Create.cshtml
@model GERNALE_WEB_APP.Core.Model.Student

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @if (ViewData["error"] != null && Convert.ToBoolean(ViewData["error"]) == true) {
            <div class="alert alert-danger" role="alert">
                @ViewData["message"]
            </div>
        }
        
        <form method="post" asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StudentNumber" class="control-label"></label>
                <input asp-for="StudentNumber" class="form-control" />
                <span asp-validation-for="StudentNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp->Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Student/Details.cshtml
@model GERNALE_WEB_APP.Core.Model.Student

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Student</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StudentNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StudentNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/Student/Edit.cshtml
@model GERNALE_WEB_APP.Core.Model.Student

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Save">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" readonly />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StudentNumber" class="control-label"></label>
                <input asp-for="StudentNumber" class="form-control" />
                <span asp-validation-for="StudentNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Student/Index.cshtml
@model IEnumerable<GERNALE_WEB_APP.Core.Model.Student>

@{
    ViewData["Title"] = "Students";
}

<h1>Index</h1>

<p>
    <a asp-controller="Student" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StudentNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                Section
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StudentNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @if (item.SectionId == 0) {
                        <p>
                            None
                        </p>
                    }
                    else {
                        @MyDatabase.sections.Find(x => x.Id == item.SectionId).Name
                    }
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.Id }, new { @class = "delete-btn"})
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    $(".delete-btn").on('click', function(event){
        event.preventDefault();
        if (confirm('Are you sure you want to delete this student record?')) {
            $.ajax({
                type: "delete",
                url: $(this).attr('href'),
                success : function(response) {
                    alert(response);
                    location.reload();
                },
                error: function(error){
                    alert(error.responseText);
                }
            });
        }
    });
</script>